
theme: jekyll-theme-tactile

exclude:
  - node_modules/

  # - !JSLib/
  - AoC/
  # - Assets/
  - Autohotkey/
  - C/
  - C++/
  - Github/
  - Java/
  # - Javascript/
  # - Multi/
  - Other/
  # - Processing/
  - Python/
  - Software/
  - Unity/
  - Web/
  - Gemfile
  - Gemfile.lock
